#!/usr/bin/env bash

# random - generate names by randomly picking from a word list
#

readonly wordlist='wordlist'

# returns random number from 0 to ($1-1) in global var 'r'.
rand() {
  local max=$(( 32768 / $1 * $1 ))
  while (( (r=$RANDOM) >= max )); do :; done
  r=$(( r % $1 ))
}

# check for a positive integer argument
if [[ -z $1 ]]; then
  printf 'Usage: ./random <integer>\n'
  printf 'Generate names by randomly picking from a word list\n'
  exit 1
else
  if [[ $1 == *[!0-9]* ]]; then
    printf '"%d" is not a positive integer\n' "$1" >&2
    exit 1
  fi
fi

# read the word list into memory, removing commented words;
# then remove the trailing empty element
unset lines n
while IFS= read -r 'lines[n++]'; do :; done < <(sed '/^#/d' "$wordlist")
[[ ${lines[n-1]} ]] || unset -v 'lines[--n]'

# output the random name(s)
for i in $(seq $1); do
  if [[ $n -eq 0 ]]; then
    printf 'No more available names left in file %s\n' "$wordlist" >&2
    exit 1
  fi

  # pick a random available word
  rand $n
  printf '%s\n' "${lines[r]}"

  # mark the word as used in the word list
  case $OSTYPE in
    darwin*)
      sed -i '' "s/^${lines[r]}\$/#${lines[r]}/" "$wordlist"
      ;;
    linux*)
      sed -i "s/^${lines[r]}\$/#${lines[r]}/" "$wordlist"
      ;;
    msys*)
      sed -i "s/^${lines[r]}\$/#${lines[r]}/" "$wordlist"
      ;;
  esac

  # remove the used word from the array to prevent duplicates
  lines=(${lines[@]:0:$r} ${lines[@]:$(( $r + 1 ))})
  n=$(( n - 1 ))
done

exit 0
